/*
 * Copyright (c) 2011-2012, Yahoo! Inc.  All rights reserved.
 * Copyrights licensed under the New BSD License.
 * See the accompanying LICENSE file for terms.
 */
var path = require('path'),
    mojito = require('mojito/lib/management/utils'),
    fs = require('fs'),
    Queue = require('buildy').Queue,
    Registry = require('buildy').Registry,
    ShakerCore = require('./core').ShakerCore,
    async = require('async'),
    mkdirp = require('mkdirp'),
    mime = require('mime'),
    utils = require('./utils');

/**
 * Shaker compiler.
 *
 * Compiler takes metadata generated by the core and depending on the environment context
 * will run tasks against the assets. Tasks including concatenating, minifying, and deploying to
 * a variety of locations (local, cdn).
 *
 * Sample application.json:
 *   ...
 *   {
 *       "settings": ["environment:test"],
 *       "shaker": {
 *           "task": "local"
 *       }
 *   },
 *   ...
 *
 * Example:
 * var store = new ResourceStore('./');
 * new Shaker(store).run(function(metadata) {
 *    console.log(metadata);
 * )});
 *
 * @param store {Object} The store object belonging to a Mojito app.
 */
function Shaker(store) {
    this._store = store;

    var config = this._store.getAppConfig(null, 'definition') || {},
        appConfig = config.staticHandling || {};

    this._prefix = '/static';
    if (typeof appConfig.prefix !== 'undefined') {
        this._prefix = appConfig.prefix ? '/' + appConfig.prefix : '';
    }

    var shaker = config.shaker !== undefined ? config.shaker : {};
    this._compile = config.shaker !== undefined; // Shaker config settings are defined in the top level of app config.
    this._task = shaker.task !== undefined ? shaker.task : 'local'; // Task to run when compiling assets
    this._images = shaker.images !== undefined ? shaker.images : false; // Deploy images
    this._parallel = shaker.parallel !== undefined ? shaker.parallel : 20;  // How many tasks the async queue runs
    this._delay = shaker.delay !== undefined ? shaker.delay : 0;    // Add some network delay for slow connections
    this._minify = shaker.minify !== undefined ? shaker.minify : true; // Uglify or not
    this._config = shaker.config !== undefined ? shaker.config : {};    // Config object passed through to task
    this._config.root = this._prefix + '/' + this._store._shortRoot + '/';  // Static prefix for assets generated
}

Shaker.TASKS_DIR = __dirname + '/tasks/';   // Tasks in this directory can be directly referenced in application.json
Shaker.ASSETS_DIR = 'assets/';
Shaker.COMPILED_DIR = Shaker.ASSETS_DIR + 'compiled/';  // Where we write the rollups
Shaker.IMAGES_DIR = Shaker.ASSETS_DIR + 'images/';

Shaker.prototype = {
    /*
     * Start compiling assets.
     *
     * @param callback {function} Callback when compiling is complete.
     */
    run: function(callback) {
        mojito.log('[SHAKER] - Analizying application assets to Shake... ');
        var metadata = new ShakerCore({store: this._store}).shakeAll();

        if (this._compile) {
            this._compileRollups(metadata, callback);
        } else {
            this._rename(metadata);
            this._writeMeta(metadata);
            callback(metadata);
        }
    },

    /*
     * Rename assets from local filename to URL.
     *
     * TODO: should be unnecessary if core keeps mapping of urls -> files
     *
     * @param metadata {Object} Core metadata to augment.
     */
    _rename: function(metadata){
        mojito.log('[SHAKER] - Processing assets for development env.');
        var mojit, action, dim, item, list;

        // Mojit assets
        for (mojit in metadata.mojits) {
            for (action in metadata.mojits[mojit]) {
                for (dim in metadata.mojits[mojit][action].shaken) {
                    for (item in metadata.mojits[mojit][action].shaken[dim]) {
                        list = metadata.mojits[mojit][action].shaken[dim];
                        list[item] = list[item].replace(this._store._root + '/mojits', this._prefix);
                    }
                }
            }
        }

        // App level assets
        for (action in metadata.app) {
            for (dim in metadata.app[action].shaken) {
                for (item in (list = metadata.app[action].shaken[dim])) {
                    var aux = list[item].replace(this._store._root, this._prefix + '/' + this._store._shortRoot);
                    aux = aux.replace(this._prefix + '/' + this._store._shortRoot + '/mojits', this._prefix);
                    list[item] = aux;
                }
            }
        }
    },

    /*
     * The workhorse of compiler. Loads the queue and processes the results. We modify the original metadata
     * object for simplicity.
     *
     * @param metadata {Object} Core metadata to augment.
     * @param callback {function} Callback when rollups are compiled.
     */
    _compileRollups: function(metadata, callback) {
        mojito.log('[SHAKER] - Compiling rollups...');

        var registry = new Registry();
        registry.load(Shaker.TASKS_DIR);

        var self = this;
        var queue = async.queue(function(item, taskCallback) {
            setTimeout(function() {
                var options = {task: self._task, minify: self._minify, config: self._config};
                item.object.push(registry, options, function(err, url) {
                    mojito.log('[SHAKER] - Pushed file ' + url);
                    item.files.push(url);
                    taskCallback();
                });
            }, self._delay);
        }, this._parallel);

        queue.drain = function() {
            self._writeMeta(metadata);
            callback(metadata);
        };

        this._queueRollups(queue, metadata);
    },

    /*
     * Add all assets referenced by metadata to an async queue.
     *
     * @param queue {Object} Queue to append tasks to.
     * @param metadata {Object} Core metadata to look through.
     */
    _queueRollups: function(queue, metadata) {
        var mojit, action, dim, files, name, client, filtered;

        // We need to add images so they can be referenced by relative URLs in the deployed CSS.
        if (this._images) {
            metadata.images.forEach(function(image) {
                queue.push({object: new Image(Shaker.IMAGES_DIR + path.basename(image), image), files: metadata.images});
            });
            metadata.images.length = 0;
        }

        // Mojito core assets
        queue.push({object: new Rollup(Shaker.COMPILED_DIR + 'core_{checksum}.common.js', metadata.core.slice() /* Clone */), files: metadata.core});
        metadata.core.length = 0;

        // Mojit assets
        for (mojit in metadata.mojits) {
            for (action in metadata.mojits[mojit]) {
                // Mojit client assets
                client = metadata.mojits[mojit][action].client;
                if (client.length) {
                    queue.push({object: new ClientRollup(Shaker.COMPILED_DIR + mojit + '_{checksum}.client.js', this._store._root, client.slice() /* Clone */), files: client});
                    client.length = 0;
                }

                for (dim in (files = metadata.mojits[mojit][action].shaken)) {
                    if (files[dim].length) {
                        name = mojit + '_' + action.replace('*', 'default') + '_{checksum}';
                        filtered = this._filterFiles(files[dim]);

                        if (filtered.js.length) {
                            queue.push({object: new Rollup(Shaker.COMPILED_DIR + name + '.common.js', filtered.js), files: files[dim]});
                        }
                        if (filtered.css.length) {
                            queue.push({object: new Rollup(Shaker.COMPILED_DIR + name + '.css', filtered.css), files: files[dim]});
                        }
                        files[dim].length = 0;
                    }
                }
            }
        }

        // App level assets
        for (action in metadata.app) {
            // App client assets
            client = metadata.app[action].client;
            if (client.length) {
                queue.push({object: new ClientRollup(Shaker.COMPILED_DIR + 'app_' + action + '_{checksum}.client.js', this._store._root, client.slice() /* Clone */), files: client});
                client.length = 0;
            }

            for (dim in (files = metadata.app[action].shaken)) {
                if (files[dim].length) {
                    name = 'app_' + action.replace('*', 'default') + '_{checksum}';
                    filtered = this._filterFiles(files[dim]);

                    if (filtered.js.length) {
                        queue.push({object: new Rollup(Shaker.COMPILED_DIR + name + '.common.js', filtered.js), files: files[dim]});
                    }
                    if (filtered.css.length) {
                        queue.push({object: new Rollup(Shaker.COMPILED_DIR + name + '.css', filtered.css), files: files[dim]});
                    }
                    files[dim].length = 0;
                }
            }
        }
    },

    /*
     * Separate JS and CSS files into separate arrays.
     *
     * @param files {array} List of JS/CSS filenames.
     */
    _filterFiles: function(files) {
        var js = [], css = [];

        files.forEach(function(file) {
            var type = mime.lookup(file);

            if (type === 'application/javascript') {
                js.push(file);
            }
            else if (type === 'text/css') {
                css.push(file);
            }
        });

        return {'js': js, 'css': css};
    },

    /*
     * Write the modified metadata.
     *
     * @param metadata {Object} Core metadata to write to file.
     */
    _writeMeta: function(metadata){
        var self = this, aux = "";
        aux += 'YUI.add("shaker/metaMojits", function(Y, NAME) {\n';
        aux += 'YUI.namespace("_mojito._cache.shaker");\n';
        aux += 'YUI._mojito._cache.shaker.meta = \n';
        aux += JSON.stringify(metadata,null,'\t');
        aux += '});';

        mojito.log('[SHAKER] - Writting addon metadata file');
        mkdirp.sync(self._store._root + '/autoload/compiled', 0777 & (~process.umask()));
        fs.writeFileSync(self._store._root + '/autoload/compiled/shaker-meta.common.js', aux);
    }
};

/*
 * Buildy wrapper for images.
 *
 * @param name {string} Name of image to build
 * @param file {string} Filename of image
 */
function Image(name, file) {
    this._name = name;
    this._file = file;
}

Image.prototype = {
    push: function(registry, options, callback) {
        var queue = new Queue(this._name, {registry: registry});

        queue.task('files', [this._file]);
        queue.task('read'); // Read the files into strings for writing

        var config = utils.simpleClone(options.config);
        config.name = this._name;
        queue.task(options.task, config);

        queue.on('taskComplete', function(data) { // queueFailed, queueComplete
            if (data.task.type === options.task) {
                callback(null, data.result);
            }
        });

        queue.run();
    }
};

/*
 * Buildy wrapper for Javascript/CSS.
 *
 * @param name {string} Name of rollup to build
 * @param files {array} Filenames to rollup
 */
function Rollup(name, files) {
    this._name = name;
    this._files = files;
}

Rollup.prototype = {
    push: function(registry, options, callback) {
        var queue = new Queue(this._name, {registry: registry});

        queue.task('files', this._files);
        queue.task('concat');

        if (options.minify) {
            queue.task(mime.lookup(this._name) === 'application/javascript' ? 'jsminify' : 'cssminify');
        }

        var config = utils.simpleClone(options.config);
        config.name = this._name;
        queue.task(options.task, config);

        queue.on('taskComplete', function(data) {
            if (data.task.type === options.task) {
                callback(null, data.result);
            }
        });

        queue.run();
    }
};

/*
 * Buildy wrapper for templates.
 *
 * @param name {string} Name of template to build
 * @param files {array} Filenames to rollup
 */
function ClientRollup(name, base, files) {
    this._name = name;
    this._base = base;
    this._files = files;
}

ClientRollup.prototype = {
    push: function(registry, options, callback) {
        var queue = new Queue(this._name, {registry: registry}),
            self = this;
        queue.task('files', this._files);

        queue.task('concatcb', {callback: function(filename, content) {
            if (mime.lookup(filename) == 'text/html') {
                var parts = filename.substring(self._base.length + 1).split('/');
                    mojit = parts[1],
                    action = parts[3].substring(0, parts[3].indexOf('.'));
                    json = JSON.stringify(content);

                content = 'YUI.add("views/' + mojit + '/' + action + '", function(Y, NAME) {\n';
                content += '\tYUI.namespace("_mojito._cache.compiled.'+ mojit +'.views");\n';
                content += '\tYUI._mojito._cache.compiled.'+ mojit +'.views.'+ action + ' = ' +  json + ';\n';
                content += '});';
            }

            return content;
        }});

        if (options.minify) {
            queue.task('jsminify');
        }

        var config = utils.simpleClone(options.config);
        config.name = this._name;
        queue.task(options.task, config);

        queue.on('taskComplete', function(data) {
            if (data.task.type === options.task) {
                callback(null, data.result);
            }
        });

        queue.run();
    }
};

exports.Shaker = Shaker;
